#!/bin/bash
pwd=`pwd`
date=`date +%Y%m%d%H%M`
if [ $# -ne 4 ]
then
  echo "Usage: `basename $0` dbhost dbport dbuser database"
  exit 65
fi
pg_dump -h$1 -p$2 -U$3 $4> ~/.didyoureadme/databasedump.sql
cd ~/
tar cvzf ~/didyoureadme_backup-$date.tar.gz .didyoureadme/
rm ~/.didyoureadme/databasedump.sql
cd $pwd
