# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'didyoureadme/ui/frmSettings.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmSettings(object):
    def setupUi(self, frmSettings):
        frmSettings.setObjectName("frmSettings")
        frmSettings.resize(485, 396)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/configure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmSettings.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(frmSettings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitulo = QtWidgets.QLabel(frmSettings)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitulo.setObjectName("lblTitulo")
        self.verticalLayout.addWidget(self.lblTitulo)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.lblPixmap = QtWidgets.QLabel(frmSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPixmap.sizePolicy().hasHeightForWidth())
        self.lblPixmap.setSizePolicy(sizePolicy)
        self.lblPixmap.setMinimumSize(QtCore.QSize(48, 48))
        self.lblPixmap.setMaximumSize(QtCore.QSize(48, 48))
        self.lblPixmap.setPixmap(QtGui.QPixmap(":/configure.png"))
        self.lblPixmap.setScaledContents(True)
        self.lblPixmap.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPixmap.setObjectName("lblPixmap")
        self.horizontalLayout_2.addWidget(self.lblPixmap)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.tab = QtWidgets.QTabWidget(frmSettings)
        self.tab.setObjectName("tab")
        self.tabGenerales = QtWidgets.QWidget()
        self.tabGenerales.setObjectName("tabGenerales")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tabGenerales)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_2 = QtWidgets.QLabel(self.tabGenerales)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.cmbLanguage = QtWidgets.QComboBox(self.tabGenerales)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbLanguage.sizePolicy().hasHeightForWidth())
        self.cmbLanguage.setSizePolicy(sizePolicy)
        self.cmbLanguage.setObjectName("cmbLanguage")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmbLanguage)
        self.label = QtWidgets.QLabel(self.tabGenerales)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.txtSupport = QtWidgets.QTextEdit(self.tabGenerales)
        self.txtSupport.setObjectName("txtSupport")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtSupport)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.tab.addTab(self.tabGenerales, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.interfaceIPLabel = QtWidgets.QLabel(self.tab_3)
        self.interfaceIPLabel.setObjectName("interfaceIPLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.interfaceIPLabel)
        self.cmbInterfaces = QtWidgets.QComboBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbInterfaces.sizePolicy().hasHeightForWidth())
        self.cmbInterfaces.setSizePolicy(sizePolicy)
        self.cmbInterfaces.setObjectName("cmbInterfaces")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmbInterfaces)
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.txtWebServerPort = QtWidgets.QLineEdit(self.tab_3)
        self.txtWebServerPort.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtWebServerPort.setObjectName("txtWebServerPort")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtWebServerPort)
        self.line = QtWidgets.QFrame(self.tab_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.line)
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.txtWebServerIP = QtWidgets.QLineEdit(self.tab_3)
        self.txtWebServerIP.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtWebServerIP.setObjectName("txtWebServerIP")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtWebServerIP)
        self.verticalLayout_4.addLayout(self.formLayout_2)
        self.tab.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.sMTPServerLabel = QtWidgets.QLabel(self.tab_2)
        self.sMTPServerLabel.setObjectName("sMTPServerLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sMTPServerLabel)
        self.txtSMTPServer = QtWidgets.QLineEdit(self.tab_2)
        self.txtSMTPServer.setObjectName("txtSMTPServer")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtSMTPServer)
        self.sMTPUserLabel = QtWidgets.QLabel(self.tab_2)
        self.sMTPUserLabel.setObjectName("sMTPUserLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.sMTPUserLabel)
        self.txtSMTPUser = QtWidgets.QLineEdit(self.tab_2)
        self.txtSMTPUser.setObjectName("txtSMTPUser")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtSMTPUser)
        self.sMTPUserLabel_2 = QtWidgets.QLabel(self.tab_2)
        self.sMTPUserLabel_2.setObjectName("sMTPUserLabel_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.sMTPUserLabel_2)
        self.txtSMTPPwd = QtWidgets.QLineEdit(self.tab_2)
        self.txtSMTPPwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtSMTPPwd.setObjectName("txtSMTPPwd")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtSMTPPwd)
        self.chkTLS = QtWidgets.QCheckBox(self.tab_2)
        self.chkTLS.setObjectName("chkTLS")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.chkTLS)
        self.fromAddressLabel = QtWidgets.QLabel(self.tab_2)
        self.fromAddressLabel.setObjectName("fromAddressLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.fromAddressLabel)
        self.txtSMTPFrom = QtWidgets.QLineEdit(self.tab_2)
        self.txtSMTPFrom.setObjectName("txtSMTPFrom")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txtSMTPFrom)
        self.txtSMTPPort = QtWidgets.QLineEdit(self.tab_2)
        self.txtSMTPPort.setObjectName("txtSMTPPort")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtSMTPPort)
        self.sMTPPortLabel = QtWidgets.QLabel(self.tab_2)
        self.sMTPPortLabel.setObjectName("sMTPPortLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.sMTPPortLabel)
        self.horizontalLayout_3.addLayout(self.formLayout)
        self.tab.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tab)
        self.buttonBox = QtWidgets.QDialogButtonBox(frmSettings)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(frmSettings)
        self.tab.setCurrentIndex(0)
        self.buttonBox.accepted.connect(frmSettings.accept)
        self.buttonBox.rejected.connect(frmSettings.reject)
        QtCore.QMetaObject.connectSlotsByName(frmSettings)

    def retranslateUi(self, frmSettings):
        _translate = QtCore.QCoreApplication.translate
        frmSettings.setWindowTitle(_translate("frmSettings", "DidYouReadMe settings"))
        self.lblTitulo.setText(_translate("frmSettings", "DidYouReadMe settings"))
        self.label_2.setText(_translate("frmSettings", "Select a language"))
        self.label.setText(_translate("frmSettings", "Support text"))
        self.txtSupport.setHtml(_translate("frmSettings", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">Please contact DidYouReadMe administrator, for any problem</span></p></body></html>"))
        self.tab.setTabText(self.tab.indexOf(self.tabGenerales), _translate("frmSettings", "Main settings"))
        self.interfaceIPLabel.setText(_translate("frmSettings", "Interface IP"))
        self.cmbInterfaces.setToolTip(_translate("frmSettings", "Web server Interface IP"))
        self.label_4.setText(_translate("frmSettings", "Server port"))
        self.txtWebServerPort.setText(_translate("frmSettings", "8000"))
        self.label_3.setText(_translate("frmSettings", "Server name/IP address for mails"))
        self.txtWebServerIP.setToolTip(_translate("frmSettings", "Must be the IP of the server, with visibility for users"))
        self.tab.setTabText(self.tab.indexOf(self.tab_3), _translate("frmSettings", "Web Server"))
        self.sMTPServerLabel.setText(_translate("frmSettings", "SMTP Server"))
        self.sMTPUserLabel.setText(_translate("frmSettings", "SMTP user"))
        self.sMTPUserLabel_2.setText(_translate("frmSettings", "SMTP password"))
        self.chkTLS.setText(_translate("frmSettings", "TLS"))
        self.fromAddressLabel.setText(_translate("frmSettings", "From address"))
        self.txtSMTPPort.setToolTip(_translate("frmSettings", "Port 25 is used to be the normal SMTP port.\n"
"If you use SSL, 465.\n"
"If you use TLS 587"))
        self.sMTPPortLabel.setText(_translate("frmSettings", "SMTP Port"))
        self.tab.setTabText(self.tab.indexOf(self.tab_2), _translate("frmSettings", "SMTP Server"))

import didyoureadme.images.didyoureadme_rc
