# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'didyoureadme/ui/frmMain.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmMain(object):
    def setupUi(self, frmMain):
        frmMain.setObjectName("frmMain")
        frmMain.setWindowModality(QtCore.Qt.ApplicationModal)
        frmMain.resize(843, 601)
        frmMain.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/didyoureadme.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmMain.setWindowIcon(icon)
        frmMain.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.wdg = QtWidgets.QWidget(frmMain)
        self.wdg.setObjectName("wdg")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.wdg)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tab = QtWidgets.QTabWidget(self.wdg)
        self.tab.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tab.setObjectName("tab")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tblGroups = myQTableWidget(self.tab_3)
        self.tblGroups.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tblGroups.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblGroups.setAlternatingRowColors(True)
        self.tblGroups.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblGroups.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblGroups.setObjectName("tblGroups")
        self.tblGroups.setColumnCount(2)
        self.tblGroups.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblGroups.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblGroups.setHorizontalHeaderItem(1, item)
        self.tblGroups.verticalHeader().setVisible(False)
        self.horizontalLayout_2.addWidget(self.tblGroups)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/group.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tab.addTab(self.tab_3, icon1, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.chkUsersInactive = QtWidgets.QCheckBox(self.tab_5)
        self.chkUsersInactive.setObjectName("chkUsersInactive")
        self.verticalLayout.addWidget(self.chkUsersInactive)
        self.tblUsers = myQTableWidget(self.tab_5)
        self.tblUsers.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tblUsers.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblUsers.setAlternatingRowColors(True)
        self.tblUsers.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblUsers.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblUsers.setObjectName("tblUsers")
        self.tblUsers.setColumnCount(0)
        self.tblUsers.setRowCount(0)
        self.tblUsers.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tblUsers)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tab.addTab(self.tab_5, icon2, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.cmbVisualization = QtWidgets.QComboBox(self.tab_2)
        self.cmbVisualization.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.cmbVisualization.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.cmbVisualization.setObjectName("cmbVisualization")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/document.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmbVisualization.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/expired.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmbVisualization.addItem(icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmbVisualization.addItem(icon5, "")
        self.horizontalLayout_6.addWidget(self.cmbVisualization)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.grpExpired = QtWidgets.QGroupBox(self.tab_2)
        self.grpExpired.setObjectName("grpExpired")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.grpExpired)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radYear = QtWidgets.QRadioButton(self.grpExpired)
        self.radYear.setChecked(False)
        self.radYear.setObjectName("radYear")
        self.horizontalLayout_4.addWidget(self.radYear)
        self.wy = wdgYear(self.grpExpired)
        self.wy.setEnabled(False)
        self.wy.setObjectName("wy")
        self.horizontalLayout_4.addWidget(self.wy)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radYearMonth = QtWidgets.QRadioButton(self.grpExpired)
        self.radYearMonth.setChecked(True)
        self.radYearMonth.setObjectName("radYearMonth")
        self.horizontalLayout_5.addWidget(self.radYearMonth)
        self.wym = wdgYearMonth(self.grpExpired)
        self.wym.setObjectName("wym")
        self.horizontalLayout_5.addWidget(self.wym)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addWidget(self.grpExpired)
        self.grpSearch = QtWidgets.QGroupBox(self.tab_2)
        self.grpSearch.setObjectName("grpSearch")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.grpSearch)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.grpSearch)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.txtSearch = QtWidgets.QLineEdit(self.grpSearch)
        self.txtSearch.setObjectName("txtSearch")
        self.horizontalLayout_7.addWidget(self.txtSearch)
        self.cmdSearch = QtWidgets.QToolButton(self.grpSearch)
        self.cmdSearch.setText("")
        self.cmdSearch.setIcon(icon5)
        self.cmdSearch.setObjectName("cmdSearch")
        self.horizontalLayout_7.addWidget(self.cmdSearch)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3.addWidget(self.grpSearch)
        self.horizontalLayout_9.addLayout(self.verticalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.tblDocuments = myQTableWidget(self.tab_2)
        self.tblDocuments.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tblDocuments.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblDocuments.setAlternatingRowColors(True)
        self.tblDocuments.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblDocuments.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblDocuments.setObjectName("tblDocuments")
        self.tblDocuments.setColumnCount(6)
        self.tblDocuments.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblDocuments.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDocuments.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDocuments.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDocuments.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDocuments.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDocuments.setHorizontalHeaderItem(5, item)
        self.tblDocuments.verticalHeader().setVisible(False)
        self.tblDocuments.verticalHeader().setHighlightSections(False)
        self.verticalLayout_4.addWidget(self.tblDocuments)
        self.horizontalLayout_10.addLayout(self.verticalLayout_4)
        self.tab.addTab(self.tab_2, icon3, "")
        self.horizontalLayout.addWidget(self.tab)
        frmMain.setCentralWidget(self.wdg)
        self.menuBar = QtWidgets.QMenuBar(frmMain)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 843, 30))
        self.menuBar.setObjectName("menuBar")
        self.menuAyuda = QtWidgets.QMenu(self.menuBar)
        self.menuAyuda.setObjectName("menuAyuda")
        self.menuJugar = QtWidgets.QMenu(self.menuBar)
        self.menuJugar.setObjectName("menuJugar")
        self.menuDocuments = QtWidgets.QMenu(self.menuBar)
        self.menuDocuments.setObjectName("menuDocuments")
        self.menuGroups = QtWidgets.QMenu(self.menuBar)
        self.menuGroups.setObjectName("menuGroups")
        self.menuU_sers = QtWidgets.QMenu(self.menuBar)
        self.menuU_sers.setObjectName("menuU_sers")
        frmMain.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(frmMain)
        self.toolBar.setObjectName("toolBar")
        frmMain.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(frmMain)
        self.statusBar.setObjectName("statusBar")
        frmMain.setStatusBar(self.statusBar)
        self.actionExit = QtWidgets.QAction(frmMain)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon6)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(frmMain)
        self.actionAbout.setIcon(icon)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSettings = QtWidgets.QAction(frmMain)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/configure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon7)
        self.actionSettings.setObjectName("actionSettings")
        self.actionHelp = QtWidgets.QAction(frmMain)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon8)
        self.actionHelp.setObjectName("actionHelp")
        self.actionUpdates = QtWidgets.QAction(frmMain)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUpdates.setIcon(icon9)
        self.actionUpdates.setObjectName("actionUpdates")
        self.actionDocumentNew = QtWidgets.QAction(frmMain)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDocumentNew.setIcon(icon10)
        self.actionDocumentNew.setObjectName("actionDocumentNew")
        self.actionDocumentDelete = QtWidgets.QAction(frmMain)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDocumentDelete.setIcon(icon11)
        self.actionDocumentDelete.setObjectName("actionDocumentDelete")
        self.actionGroupNew = QtWidgets.QAction(frmMain)
        self.actionGroupNew.setIcon(icon10)
        self.actionGroupNew.setObjectName("actionGroupNew")
        self.actionGroupDelete = QtWidgets.QAction(frmMain)
        self.actionGroupDelete.setIcon(icon11)
        self.actionGroupDelete.setObjectName("actionGroupDelete")
        self.actionGroupEdit = QtWidgets.QAction(frmMain)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/editar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGroupEdit.setIcon(icon12)
        self.actionGroupEdit.setObjectName("actionGroupEdit")
        self.actionUserNew = QtWidgets.QAction(frmMain)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/user-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUserNew.setIcon(icon13)
        self.actionUserNew.setObjectName("actionUserNew")
        self.actionUserDelete = QtWidgets.QAction(frmMain)
        self.actionUserDelete.setIcon(icon11)
        self.actionUserDelete.setObjectName("actionUserDelete")
        self.actionUserEdit = QtWidgets.QAction(frmMain)
        self.actionUserEdit.setIcon(icon12)
        self.actionUserEdit.setObjectName("actionUserEdit")
        self.actionTablesUpdate = QtWidgets.QAction(frmMain)
        self.actionTablesUpdate.setIcon(icon9)
        self.actionTablesUpdate.setObjectName("actionTablesUpdate")
        self.actionDocumentExpire = QtWidgets.QAction(frmMain)
        self.actionDocumentExpire.setIcon(icon4)
        self.actionDocumentExpire.setObjectName("actionDocumentExpire")
        self.actionDocumentReport = QtWidgets.QAction(frmMain)
        self.actionDocumentReport.setIcon(icon3)
        self.actionDocumentReport.setObjectName("actionDocumentReport")
        self.actionDocumentOpen = QtWidgets.QAction(frmMain)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDocumentOpen.setIcon(icon14)
        self.actionDocumentOpen.setObjectName("actionDocumentOpen")
        self.actionDocumentDeleteAdmin = QtWidgets.QAction(frmMain)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/admin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDocumentDeleteAdmin.setIcon(icon15)
        self.actionDocumentDeleteAdmin.setObjectName("actionDocumentDeleteAdmin")
        self.actionSendAgain = QtWidgets.QAction(frmMain)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/mail.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSendAgain.setIcon(icon16)
        self.actionSendAgain.setObjectName("actionSendAgain")
        self.actionDocumentsPurge = QtWidgets.QAction(frmMain)
        self.actionDocumentsPurge.setIcon(icon15)
        self.actionDocumentsPurge.setObjectName("actionDocumentsPurge")
        self.menuAyuda.addAction(self.actionHelp)
        self.menuAyuda.addSeparator()
        self.menuAyuda.addAction(self.actionUpdates)
        self.menuAyuda.addSeparator()
        self.menuAyuda.addAction(self.actionAbout)
        self.menuJugar.addAction(self.actionTablesUpdate)
        self.menuJugar.addSeparator()
        self.menuJugar.addAction(self.actionSettings)
        self.menuJugar.addSeparator()
        self.menuJugar.addAction(self.actionExit)
        self.menuDocuments.addAction(self.actionDocumentNew)
        self.menuDocuments.addSeparator()
        self.menuDocuments.addSeparator()
        self.menuDocuments.addAction(self.actionDocumentsPurge)
        self.menuGroups.addAction(self.actionGroupNew)
        self.menuU_sers.addAction(self.actionUserNew)
        self.menuBar.addAction(self.menuJugar.menuAction())
        self.menuBar.addAction(self.menuGroups.menuAction())
        self.menuBar.addAction(self.menuU_sers.menuAction())
        self.menuBar.addAction(self.menuDocuments.menuAction())
        self.menuBar.addAction(self.menuAyuda.menuAction())
        self.toolBar.addAction(self.actionDocumentNew)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionTablesUpdate)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSettings)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHelp)
        self.toolBar.addAction(self.actionAbout)

        self.retranslateUi(frmMain)
        self.tab.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(frmMain)

    def retranslateUi(self, frmMain):
        _translate = QtCore.QCoreApplication.translate
        item = self.tblGroups.horizontalHeaderItem(0)
        item.setText(_translate("frmMain", "Name"))
        item = self.tblGroups.horizontalHeaderItem(1)
        item.setText(_translate("frmMain", "Users"))
        self.tab.setTabText(self.tab.indexOf(self.tab_3), _translate("frmMain", "Groups"))
        self.chkUsersInactive.setText(_translate("frmMain", "Show inactive users"))
        self.tab.setTabText(self.tab.indexOf(self.tab_5), _translate("frmMain", "Users"))
        self.label.setText(_translate("frmMain", "Select a visualization mode"))
        self.cmbVisualization.setItemText(0, _translate("frmMain", "Active documents"))
        self.cmbVisualization.setItemText(1, _translate("frmMain", "Expired documents"))
        self.cmbVisualization.setItemText(2, _translate("frmMain", "Search documents"))
        self.grpExpired.setTitle(_translate("frmMain", "List options for expired documents"))
        self.radYear.setText(_translate("frmMain", "Show e&xpired documents from selected year"))
        self.radYearMonth.setText(_translate("frmMain", "Show expired documents from selected year and month"))
        self.grpSearch.setTitle(_translate("frmMain", "Search documents"))
        self.label_2.setText(_translate("frmMain", "Write a string to search"))
        item = self.tblDocuments.horizontalHeaderItem(0)
        item.setText(_translate("frmMain", "Datetime"))
        item = self.tblDocuments.horizontalHeaderItem(1)
        item.setText(_translate("frmMain", "Planned"))
        item = self.tblDocuments.horizontalHeaderItem(2)
        item.setText(_translate("frmMain", "Sent"))
        item = self.tblDocuments.horizontalHeaderItem(3)
        item.setText(_translate("frmMain", "Read"))
        item = self.tblDocuments.horizontalHeaderItem(4)
        item.setText(_translate("frmMain", "Expiration"))
        item = self.tblDocuments.horizontalHeaderItem(5)
        item.setText(_translate("frmMain", "Title"))
        self.tab.setTabText(self.tab.indexOf(self.tab_2), _translate("frmMain", "Documents"))
        self.menuAyuda.setTitle(_translate("frmMain", "He&lp"))
        self.menuJugar.setTitle(_translate("frmMain", "S&ystem"))
        self.menuDocuments.setTitle(_translate("frmMain", "&Documents"))
        self.menuGroups.setTitle(_translate("frmMain", "&Groups"))
        self.menuU_sers.setTitle(_translate("frmMain", "&Users"))
        self.toolBar.setWindowTitle(_translate("frmMain", "toolBar"))
        self.actionExit.setText(_translate("frmMain", "E&xit"))
        self.actionExit.setToolTip(_translate("frmMain", "Exit"))
        self.actionExit.setShortcut(_translate("frmMain", "Esc"))
        self.actionAbout.setText(_translate("frmMain", "&About DidYouReadMe"))
        self.actionAbout.setToolTip(_translate("frmMain", "About DidYouReadMe"))
        self.actionSettings.setText(_translate("frmMain", "&Settings"))
        self.actionSettings.setToolTip(_translate("frmMain", "Settings"))
        self.actionHelp.setText(_translate("frmMain", "&Help"))
        self.actionHelp.setToolTip(_translate("frmMain", "Help"))
        self.actionHelp.setShortcut(_translate("frmMain", "F1"))
        self.actionUpdates.setText(_translate("frmMain", "&Look for updates"))
        self.actionUpdates.setToolTip(_translate("frmMain", "Look for updates"))
        self.actionDocumentNew.setText(_translate("frmMain", "&New Document"))
        self.actionDocumentDelete.setText(_translate("frmMain", "Delete Document"))
        self.actionDocumentDelete.setToolTip(_translate("frmMain", "Delete Document"))
        self.actionGroupNew.setText(_translate("frmMain", "&New Group"))
        self.actionGroupNew.setToolTip(_translate("frmMain", "New Group"))
        self.actionGroupDelete.setText(_translate("frmMain", "Delete Group"))
        self.actionGroupDelete.setToolTip(_translate("frmMain", "Delete Group"))
        self.actionGroupEdit.setText(_translate("frmMain", "Edit Group"))
        self.actionGroupEdit.setToolTip(_translate("frmMain", "Edit Group"))
        self.actionUserNew.setText(_translate("frmMain", "&New User"))
        self.actionUserNew.setToolTip(_translate("frmMain", "New User"))
        self.actionUserDelete.setText(_translate("frmMain", "Delete User"))
        self.actionUserDelete.setToolTip(_translate("frmMain", "Delete User"))
        self.actionUserEdit.setText(_translate("frmMain", "Edit User"))
        self.actionUserEdit.setToolTip(_translate("frmMain", "Edit User"))
        self.actionTablesUpdate.setText(_translate("frmMain", "&Update tables"))
        self.actionTablesUpdate.setToolTip(_translate("frmMain", "Update tables"))
        self.actionDocumentExpire.setText(_translate("frmMain", "Expire document"))
        self.actionDocumentExpire.setToolTip(_translate("frmMain", "Expire document"))
        self.actionDocumentReport.setText(_translate("frmMain", "Generate report"))
        self.actionDocumentReport.setToolTip(_translate("frmMain", "Generate report"))
        self.actionDocumentOpen.setText(_translate("frmMain", "Open document"))
        self.actionDocumentOpen.setToolTip(_translate("frmMain", "Open document"))
        self.actionDocumentDeleteAdmin.setText(_translate("frmMain", "Delete document by Administrator"))
        self.actionDocumentDeleteAdmin.setToolTip(_translate("frmMain", "Delete document by administrator"))
        self.actionSendAgain.setText(_translate("frmMain", "Send document again"))
        self.actionSendAgain.setToolTip(_translate("frmMain", "Send document again"))
        self.actionDocumentsPurge.setText(_translate("frmMain", "&Documents purge by Administrator"))
        self.actionDocumentsPurge.setToolTip(_translate("frmMain", "Documents purge by Administrator"))

from didyoureadme.ui.myqtablewidget import myQTableWidget
from didyoureadme.ui.wdgYear import wdgYear
from didyoureadme.ui.wdgYearMonth import wdgYearMonth
import didyoureadme.images.didyoureadme_rc
