# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'didyoureadme/ui/wdgDocumentsSearch.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_wdgDocumentsSearch(object):
    def setupUi(self, wdgDocumentsSearch):
        wdgDocumentsSearch.setObjectName("wdgDocumentsSearch")
        wdgDocumentsSearch.resize(835, 646)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(wdgDocumentsSearch)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblApp = QtWidgets.QLabel(wdgDocumentsSearch)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblApp.setFont(font)
        self.lblApp.setAlignment(QtCore.Qt.AlignCenter)
        self.lblApp.setObjectName("lblApp")
        self.verticalLayout.addWidget(self.lblApp)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(wdgDocumentsSearch)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.txtSearch = QtWidgets.QLineEdit(wdgDocumentsSearch)
        self.txtSearch.setObjectName("txtSearch")
        self.horizontalLayout.addWidget(self.txtSearch)
        self.cmdSearch = QtWidgets.QToolButton(wdgDocumentsSearch)
        self.cmdSearch.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdSearch.setIcon(icon)
        self.cmdSearch.setObjectName("cmdSearch")
        self.horizontalLayout.addWidget(self.cmdSearch)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tblDocuments = myQTableWidget(wdgDocumentsSearch)
        self.tblDocuments.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tblDocuments.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblDocuments.setAlternatingRowColors(True)
        self.tblDocuments.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblDocuments.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblDocuments.setObjectName("tblDocuments")
        self.tblDocuments.setColumnCount(0)
        self.tblDocuments.setRowCount(0)
        self.verticalLayout.addWidget(self.tblDocuments)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.actionDocumentReport = QtWidgets.QAction(wdgDocumentsSearch)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/document.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDocumentReport.setIcon(icon1)
        self.actionDocumentReport.setObjectName("actionDocumentReport")
        self.actionDocumentOpen = QtWidgets.QAction(wdgDocumentsSearch)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDocumentOpen.setIcon(icon2)
        self.actionDocumentOpen.setObjectName("actionDocumentOpen")
        self.actionDocumentExpire = QtWidgets.QAction(wdgDocumentsSearch)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/expired.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDocumentExpire.setIcon(icon3)
        self.actionDocumentExpire.setObjectName("actionDocumentExpire")
        self.actionSendAgain = QtWidgets.QAction(wdgDocumentsSearch)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/mail.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSendAgain.setIcon(icon4)
        self.actionSendAgain.setObjectName("actionSendAgain")
        self.actionDocumentDeleteAdmin = QtWidgets.QAction(wdgDocumentsSearch)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/admin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDocumentDeleteAdmin.setIcon(icon5)
        self.actionDocumentDeleteAdmin.setObjectName("actionDocumentDeleteAdmin")

        self.retranslateUi(wdgDocumentsSearch)
        QtCore.QMetaObject.connectSlotsByName(wdgDocumentsSearch)

    def retranslateUi(self, wdgDocumentsSearch):
        _translate = QtCore.QCoreApplication.translate
        wdgDocumentsSearch.setWindowTitle(_translate("wdgDocumentsSearch", "Form"))
        self.lblApp.setText(_translate("wdgDocumentsSearch", "Search documents"))
        self.label.setText(_translate("wdgDocumentsSearch", "Write a string to search"))
        self.actionDocumentReport.setText(_translate("wdgDocumentsSearch", "Generate report"))
        self.actionDocumentReport.setToolTip(_translate("wdgDocumentsSearch", "Generate report"))
        self.actionDocumentOpen.setText(_translate("wdgDocumentsSearch", "Open document"))
        self.actionDocumentOpen.setToolTip(_translate("wdgDocumentsSearch", "Open document"))
        self.actionDocumentExpire.setText(_translate("wdgDocumentsSearch", "Expire document"))
        self.actionDocumentExpire.setToolTip(_translate("wdgDocumentsSearch", "Expire document"))
        self.actionSendAgain.setText(_translate("wdgDocumentsSearch", "Send document again"))
        self.actionSendAgain.setToolTip(_translate("wdgDocumentsSearch", "Send document again"))
        self.actionDocumentDeleteAdmin.setText(_translate("wdgDocumentsSearch", "Delete document by Administrator"))
        self.actionDocumentDeleteAdmin.setToolTip(_translate("wdgDocumentsSearch", "Delete document by administrator"))

from didyoureadme.ui.myqtablewidget import myQTableWidget
import didyoureadme.images.didyoureadme_rc
